// SPDX-License-Identifier: Apache-2.0
#pragma once

namespace mhw {

// Official localized name for a Rise monster, keyed by the HunterPie schema
// Id that the game keeps at monster + 0x2D4 (MHRGame.cs:305-324 reads the same
// field, and MHRMonster.cs:46-48 turns it into a name).
//
// Source (provenance — the table is generated by
// scripts/extract_rise_monster_names.py, which sha256-verifies both files):
//   HunterPie official localization
//     https://cdn.hunterpie.com/localization/zh-cn.xml
//     sha256 2a4b1bb318fc21a55c0b5b978e2d33cb8c2ea74457b34fcac88b9236c19a06db
//     https://cdn.hunterpie.com/localization/en-us.xml
//     sha256 661d58b54bd1214ae0e9eff92fb4167b8aab54df0452eea238cb9574300030ea
//   byte-identical to HunterPie/localization@main/localization/<lang>.xml and to
//   the hashes published by https://api.hunterpie.com/v1/localization/checksum.
//   Extracted from `zh-cn.xml` lines 981-1140 and `en-us.xml` lines 964-1123 —
//   the <Rise> child of the top-level <Monsters> block, i.e.
//   /Strings/Monsters/Rise/Monster[@Id] — 79 entries, Id 0..46 / 76..98 /
//   107..115 in both locales (the generator asserts the Id sets are equal).
//
// The lookup mirrors HunterPie exactly:
//   MHRMonster.cs:48
//     Name = localizationRepository.FindStringBy(
//         $"//Strings/Monsters/Rise/Monster[@Id='{Id}']")
// so these are the strings a mature Rise overlay shows in-game.
//
// Locale selection (v0.9 i18n, WS-B): riseMonsterName() returns the en-us.xml
// column while mhw::StringTable::instance().isEnglish() is true, and the
// zh-cn.xml column otherwise. An empty locale (before any load()) reads as
// Chinese, so the pre-i18n behaviour is the default.
//
// Returns nullptr when the localization file has no entry for `id` (the id
// gaps 47..75 / 99..106 and anything outside 0..115 are upstream and real);
// callers fall back to "Monster #<id>". Never returns an empty string.
const char *riseMonsterName(int id);

// The en-us.xml column, independent of the active locale (tests / tooling).
// nullptr under exactly the same conditions as riseMonsterName().
const char *riseMonsterNameEn(int id);

} // namespace mhw
