#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""One-shot migration: split the 2-domain i18n tree into the 4 v0.11.0 domains.

Domain routing follows docs/I18N.md §2 — the criterion is WHO REPAINTS the
string, not which process reads it:

  overlay.json  ui.* overlay panel chrome (painted every frame)
  console.json  console.* console chrome (replayed by retranslateUi)
  reader.json   ui.reader.* (snapshot status, per-poll refresh)
  data.json     mantle.* / abnormality.* / ui.demo.* (pure data ids)

*** KEY NAMES ARE PRESERVED VERBATIM *** — including the `ui.` prefix on
reader and demo keys. That is deliberate. The audit (i18n-audit.md §5.3) and
PLAN.md (B8) both schedule the three-layer rename (`ui.reader.*` ->
`reader.*`, `ui.demo.*` -> `demo.*`, `ui.*` -> `overlay.panel.*`) as a
SEPARATE later batch, because that batch must change ~150 call sites in
src/**/*.cpp — files this task is not allowed to touch (see TASK_SPEC below).
Moving a key without moving its caller turns a live key into a missing key:
StringTable::tr() would silently return the dot-path and the overlay would
paint "ui.reader.waiting_exe" instead of a sentence. So this script does the
half that is safe alone — the file split — and leaves the call sites for T2.

Dead keys are DROPPED, never moved. The list is DEAD_KEYS below: every entry
was verified dead by scripts/i18n_unused_keys.py --tests and cross-checked by
hand against the four reference channels the regex gate scripts cannot see:

  * `kKeys[]` / `kNameKeys[]` / `kCorners[]` static arrays in code
    (panel_sections.h, hud_canvas.cpp) — plain literals, so the literal scan
    covers them; verified none of the dropped keys appear there.
  * `const char *stateKey = "...": "..."` ternary chains (control_panel.cpp
    :2188, :2300) — also plain literals, same coverage.
  * `QStringLiteral("mantle.%1").arg(id)` composed keys (string_table.h) —
    matched by the prefix rule in i18n_unused_keys.py, so all 21 mantle ids
    are correctly considered reachable and NONE of them is in DEAD_KEYS.
  * the tests/ tree (locale_sync_tests.cpp, snap_player_offline.cpp, ...),
    which keeps ui.app_title and ui.context_hunting alive.

Usage (from the repo root):
    python3 scripts/i18n_split_domains.py [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
I18N = REPO / "src/resources/i18n"
QRC = REPO / "src/resources/resources.qrc"

LOCALES = ("zh-CN", "en-US")
DOMAINS = ("overlay", "console", "reader", "data")
SKIP_KEYS = ("_meta", "_comment")

# Dead keys, one verified category each. Generated by
#   scripts/i18n_unused_keys.py --tests --emit-dead-keys
# and every entry cross-checked by hand against the reference channels that
# the regex-based gate scripts cannot see (kKeys[]/kNameKeys[] static arrays,
# `const char *stateKey = "..."` ternary chains, and `mantle.%1`.arg(id)
# composition). Verified dead src+tests: 84 keys.
DEAD_KEYS = frozenset({
    # ---- ui.zone_* (38): the whole World/Rise zone-name block. ------------
    # Every value is already a row in src/world/world_types.cpp's zoneName()
    # / zoneNameEn() tables, which is what zoneNameLocalized() reads. These
    # keys have had 0 references since they were added; the audit calls out
    # this block as the largest dead cluster (audit/i18n-audit.md §5.3).
    "ui.zone_ancient_forest", "ui.zone_ancient_forest_2", "ui.zone_arena",
    "ui.zone_astera", "ui.zone_astera_gathering_hub",
    "ui.zone_castle_schrade", "ui.zone_caverns_of_el_dorado",
    "ui.zone_chamber_of_five", "ui.zone_confluence_of_fates",
    "ui.zone_coral_highlands", "ui.zone_elders_recess",
    "ui.zone_everstream", "ui.zone_great_ravine", "ui.zone_great_ravine_2",
    "ui.zone_guiding_lands", "ui.zone_hoarfrost_reach", "ui.zone_introduction",
    "ui.zone_living_quarters", "ui.zone_main_menu", "ui.zone_origin_isle",
    "ui.zone_origin_isle_2", "ui.zone_private_quarters",
    "ui.zone_private_suite", "ui.zone_research_base", "ui.zone_rotten_vale",
    "ui.zone_secluded_valley", "ui.zone_secluded_valley_2",
    "ui.zone_seliana", "ui.zone_seliana_gathering_hub",
    "ui.zone_seliana_room", "ui.zone_seliana_supply_cache",
    "ui.zone_seliana_supply_cache_2", "ui.zone_special_arena",
    "ui.zone_wildspire_waste",
    # NOTE: ui.zone_unknown is NOT in this set — panel_player.cpp:190/204 uses
    # it as a sentinel (tr(key)==key means "no zone"). Neither are
    # ui.zone_unknown_area, ui.zone_outpost or ui.zone_area: live literals.
    # ---- abnormality.* (7): superseded by the trait/name tables. ----------
    "abnormality.earplug", "abnormality.mantle_health",
    "abnormality.mantle_health_large", "abnormality.mantle_stamina",
    "abnormality.mantle_stamina_large", "abnormality.mantle_tool",
    "abnormality.mantle_tool_large",
    # ---- console (1): replaced by console.reframework.stateLuaMissing. ----
    "console.reframework.luaMissing",
    # ---- ui.* format fragments (38): their call sites were rewritten when
    # the panels moved to C++ formatters (src/ui/formatters.*), so these
    # templates have no caller left. Each was grepped across src/ AND tests/.
    "ui.buildup_suffix", "ui.context_disconnected",
    "ui.context_disconnected_long", "ui.context_hunting_no_quest",
    "ui.context_main_menu", "ui.context_peace", "ui.context_training_area",
    "ui.context_unknown", "ui.enrage_buildup", "ui.enrage_suffix",
    "ui.font_family", "ui.hp_total_unknown", "ui.hp_total_with_suffix",
    "ui.mantle_active", "ui.mantle_cooldown", "ui.mantle_label_default",
    "ui.monster_default_name", "ui.monster_id_label", "ui.monster_no_data",
    "ui.no_party", "ui.object_scope", "ui.part_break_multi",
    "ui.part_break_solo", "ui.part_breakable_tag", "ui.part_broken_suffix",
    "ui.part_flinch_multi", "ui.part_flinch_solo", "ui.part_name_padded",
    "ui.part_sever_multi", "ui.part_sever_solo", "ui.part_severable_tag",
    "ui.party_line", "ui.percentage_format", "ui.percentage_unavailable",
    "ui.player_gear_prefix", "ui.player_gear_separator", "ui.player_header",
    "ui.quest_active", "ui.quest_inactive", "ui.seconds_format",
    "ui.seconds_unavailable", "ui.status_default",
})

META_NOTES = {
    "zh-CN": {
        "overlay": "悬浮窗面板 chrome：ui.* 中由各面板 paintPanel() 每次重绘重新 "
                   "tr() 的文案（panel_* / *_title / *_header / status_* …）。"
                   "注意 v0.11.0 起 key 名暂未三层化，改名批次（PLAN.md B8）"
                   "另做，届时 reader/demo 的 ui. 前缀一并去掉。",
        "console": "控制台 chrome：console.*，由 ControlPanel::retranslateUi() "
                   "重放 trPairs_/trTips_/trHooks_ 注册表。",
        "reader": "reader 上屏状态 / 诊断文案：snapshot.status 每个 poll tick "
                  "自然刷新，不依赖任何注册表。key 暂留 ui.reader.* 前缀，"
                  "改名批次会改成 reader.*。",
        "data": "数据名与演示数据：mantle.*（衣装名）/ abnormality.*（异常别名）/ "
                "ui.demo.*（console 舞台预览种子）。纯 id→string；占位符只在 "
                "ui.demo.* 出现，router 侧会 tr() 后 .arg()。",
    },
    "en-US": {
        "overlay": "Overlay panel chrome: the ui.* strings re-tr()'d by each "
                   "panel's paintPanel() on every repaint. Key names keep the "
                   "ui. prefix until the rename batch (PLAN.md B8).",
        "console": "Console chrome: console.*, replayed by "
                   "ControlPanel::retranslateUi() across the trPairs_/"
                   "trTips_/trHooks_ registries.",
        "reader": "Reader on-screen status / diagnostics: snapshot.status is "
                  "refreshed on every poll tick, no registry involved. Keys "
                  "keep the ui.reader.* prefix until the rename batch.",
        "data": "Data names and demo seed data: mantle.* / abnormality.* / "
                "ui.demo.*. Mostly pure id->string; ui.demo.* entries carry "
                "%N placeholders and are .arg()'d at the call site.",
    },
}


def flatten(obj: dict, prefix: str = "") -> dict:
    """Nested object -> dot-path leaves, identical to StringTable::load()."""
    out = {}
    for key, value in obj.items():
        if key in SKIP_KEYS:
            continue
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            out.update(flatten(value, path))
        else:
            out[path] = value
    return out


def nest(flat: dict) -> dict:
    """dot-path flat map -> nested dict so the JSON stays readable."""
    root: dict = {}
    for key, value in flat.items():
        parts = key.split(".")
        node = root
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    return root


def route(key: str, value, dead: set):
    """Return (domain, new_key) or None when the key must be dropped.

    The key is NOT renamed — see the module docstring. Only the file changes.
    """
    if key in dead:
        return None
    if key.startswith("ui.reader."):
        return ("reader", key)
    if key.startswith("ui.demo."):
        return ("data", key)
    if key.startswith("mantle.") or key.startswith("abnormality."):
        return ("data", key)
    if key.startswith("console."):
        return ("console", key)
    # Everything else under ui.* is overlay panel chrome.
    return ("overlay", key)


def split_locale(locale: str, dead: set) -> dict:
    src = I18N / locale
    overlay = json.loads((src / "overlay.json").read_text(encoding="utf-8"))
    console = json.loads((src / "console.json").read_text(encoding="utf-8"))
    parts = {d: {} for d in DOMAINS}
    for key, value in {**flatten(overlay), **flatten(console)}.items():
        routed = route(key, value, dead)
        if routed is None:
            continue
        domain, new_key = routed
        parts[domain][new_key] = value
    return parts


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true",
                    help="print the routing table; write nothing")
    args = ap.parse_args(argv)

    dead = set(DEAD_KEYS)
    print(f"dropping {len(dead)} dead key(s)")

    for locale in LOCALES:
        parts = split_locale(locale, dead)
        print(f"\n{locale}:")
        for domain in DOMAINS:
            flat = parts[domain]
            print(f"  {domain}.json: {len(flat)} keys")
            # Invariant on every run: a dead key must never be carried over.
            bad = sorted(k for k in flat if k in dead)
            if bad:
                print(f"  !! LEAKED DEAD KEYS: {bad}", file=sys.stderr)
                return 1
            if args.dry_run:
                continue
            doc = {}
            note = META_NOTES[locale][domain]
            if note:
                doc["_meta"] = note
            doc.update(nest(flat))
            (I18N / locale / f"{domain}.json").write_text(
                json.dumps(doc, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8")

    if args.dry_run:
        return 0

    # The 2→4 split needs 8 files listed; rebuild the i18n block of the qrc.
    qrc = QRC.read_text(encoding="utf-8", errors="strict") if QRC.exists() else ""
    if not qrc:
        print(f"FAIL: unreadable {QRC}", file=sys.stderr)
        return 1
    kept = [ln for ln in qrc.splitlines(keepends=True)
            if not re.match(r"\s*<file>i18n/.*\.json</file>", ln)]
    entries = "".join(f"        <file>i18n/{loc}/{dom}.json</file>\n"
                      for loc in LOCALES for dom in DOMAINS)
    # NOTE (v0.11.0): this script already ran and its job is done. The
    # anchor below was the qrc layout of that time — monsters/parts.json has
    # since been deleted, so a fresh run now fails at the anchor check below.
    # That is expected: do NOT re-run this against the current tree. The
    # four-domain i18n layout it produced is the shipped state.
    anchor = "        <file>monsters/parts.json</file>\n"
    text2 = "".join(kept)
    if anchor not in text2:
        print(f"FAIL: qrc anchor not found: {anchor!r}", file=sys.stderr)
        return 1
    QRC.write_text(text2.replace(anchor, entries + anchor, 1), encoding="utf-8")

    # NOTE: there is nothing to delete. The 2→4 split keeps the SAME file
    # names for overlay/console (they are the domain names, not the old
    # process-oriented names), so the four files written above ARE the final
    # state. The pre-split content lived in exactly these paths and has been
    # overwritten — the old `unlink()` of the same paths here used to delete
    # the freshly-written files and leave only reader/data on disk.
    print("\nsplit complete: 4 domains x 2 locales")
    return 0


if __name__ == "__main__":
    sys.exit(main())
