#include "monster/monster_types.h"
#include <QHash>

namespace mhw {

extern const QHash<int, QVector<PartSchema>> kPartSchemas = {
    {0, {
        { 1, true, "喉咙", "Throat", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "5", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左腿", "Left Leg", false, "3", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右腿", "Right Leg", false, "3", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {1, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {4, {
        { 0, true, "击退", "Repel", true, "" },
        { 1, false, "头部", "Head", false, "1" },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "胸部", "Chest", true, "1" },
        { 4, false, "左臂", "Left Arm", false, "" },
        { 5, false, "右臂", "Right Arm", false, "" },
        { 6, false, "左腿", "Left Leg", false, "" },
        { 7, false, "右腿", "Right Leg", false, "" },
        { 8, false, "尾巴", "Tail", false, "" },
        { 9, false, "壳", "Shell", false, "" },
        { 10, false, "排气管（中）", "Exhaust Organ (Central)", true, "1" },
        { 11, false, "排气管（头）", "Exhaust Organ (Head)", true, "1" },
        { 12, false, "排气管 (坑)", "Exhaust Organ (Crater)", true, "1" },
        { 13, false, "排气管（后）", "Exhaust Organ (Rear)", true, "1" },
        { 14, false, "左弱壳", "Left Weak Shell", true, "1" },
        { 15, false, "右弱壳", "Right Weak Shell", true, "1" },
    }},
    {7, {
        { 0, false, "头部", "Head", false, "2", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Body", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "手臂", "Arms", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "腿", "Legs", false, "" },
        { 4, false, "尾巴", "Tail", false, "" },
        { 5, false, "腹部", "Abdomen", true, "3" },
    }},
    {9, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {10, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {11, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {12, {
        { 0, true, "角", "Horns", false, "1,2" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左翼", "Left Wing", false, "" },
        { 5, false, "右翼", "Right Wing", false, "" },
        { 6, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {13, {
        { 0, true, "角", "Horns", false, "1,2" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左翼", "Left Wing", false, "" },
        { 5, false, "右翼", "Right Wing", false, "" },
        { 6, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {14, {
        { 0, false, "角", "Horn", false, "1", {0x0u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "手臂", "Arms", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "腿", "Legs", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {15, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "角", "Horns", false, "2,3" },
        { 2, false, "头部", "Head", false, "", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "" },
        { 4, false, "左臂", "Left Arm", false, "3", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右臂", "Right Arm", false, "3", {0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "左腿", "Left Leg", false, "" },
        { 7, false, "右腿", "Right Leg", false, "" },
        { 8, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {16, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左肢", "Left Limbs", true, "" },
        { 5, false, "右肢", "Right Limbs", true, "" },
        { 6, false, "翼", "Wings", false, "2", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {17, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "1", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "四肢", "Limbs", true, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左翼", "Left Wing", false, "2", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右翼", "Right Wing", false, "2", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {18, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "角", "Horns", false, "" },
        { 2, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "" },
        { 4, false, "手臂", "Arms", false, "" },
        { 5, false, "腿", "Legs", false, "" },
        { 6, false, "翼", "Wings", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {19, {
        { 0, false, "头部", "Head", false, "6", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Body", false, "2", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "腹部", "Abdomen", true, "" },
        { 3, false, "左腿", "Left Leg", false, "4" },
        { 4, false, "右腿", "Right Leg", false, "4" },
        { 5, false, "尾巴", "Tail", false, "4", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {20, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "大退缩", "Big Flinch", true, "" },
        { 2, false, "头部", "Head", false, "3", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "胸部", "Chest", true, "5" },
        { 5, false, "臀部", "Rear", false, "" },
        { 6, false, "手臂", "Arms", false, "" },
        { 7, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {21, {
        { 0, true, "头部", "Head", false, "1" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "头部(泥土)", "Head (Mud)", true, "1", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "身体(泥土)", "Body (Mud)", true, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "手臂", "Arms", false, "1" },
        { 7, false, "手臂(泥土)", "Arms (Mud)", true, "1" },
        { 8, false, "左腿", "Left Leg", false, "1", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "左腿(泥土)", "Left Leg (Mud)", true, "1", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 10, false, "右腿", "Right Leg", false, "1", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 11, false, "右腿(泥土)", "Right Leg (Mud)", true, "1", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 12, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 13, false, "尾巴(泥土)", "Tail (Mud)", true, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {22, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "颚", "Jaw", true, "1" },
        { 2, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "手臂", "Arms", false, "" },
        { 5, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {23, {
        { 0, true, "身体和腿", "Body & Legs", true, "1" },
        { 1, false, "鹿角", "Antlers", true, "1,2", {0x0u, 0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "", {0x0u, 0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "腿", "Legs", false, "" },
        { 4, false, "手臂", "Arms", false, "" },
        { 5, false, "???", "???", true, "" },
    }},
    {24, {
        { 0, true, "头部", "Head", false, "" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1" },
        { 4, false, "左翼", "Left Wing", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右翼", "Right Wing", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {25, {
        { 0, true, "角", "Horns", false, "2,3" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, true, "???", "???", true, "" },
        { 3, false, "角", "Horns", false, "" },
        { 4, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "身体", "Body", false, "" },
        { 6, false, "左臂", "Left Arm", false, "", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "" },
        { 9, false, "右腿", "Right Leg", false, "" },
        { 10, false, "左翼", "Left Wing", false, "", {0x2u, 0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 11, false, "右翼", "Right Wing", false, "", {0x6u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 12, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {26, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "???", "???", true, "" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "颈部", "Neck", false, "" },
        { 4, false, "背部", "Back", false, "" },
        { 5, false, "胸部", "Chest", true, "" },
        { 6, false, "左臂", "Left Arm", false, "2", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "2", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "" },
        { 9, false, "右腿", "Right Leg", false, "" },
        { 10, false, "翼", "Wings", false, "2", {0x2u, 0x6u, 0x8u, 0x9u}, 4u },
        { 11, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {27, {
        { 0, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "手臂", "Arms", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "腿", "Legs", false, "" },
        { 3, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "石头", "Rock", true, "" },
    }},
    {28, {
        { 0, false, "头部", "Head", false, "2" },
        { 1, false, "头部", "Head", false, "", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "手臂", "Arms", false, "", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "腿", "Legs", false, "" },
        { 4, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {29, {
        { 0, false, "头部", "Head", false, "4", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Torso", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "左腿", "Left Leg", false, "2" },
        { 3, false, "右腿", "Right Leg", false, "2" },
        { 4, false, "尾巴", "Tail", false, "3", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "头部(泥土)", "Head (Mud)", true, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "躯干(泥土)", "Torso (Mud)", true, "3", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "左腿(泥土)", "Left Leg (Mud)", true, "2" },
        { 8, false, "右腿(泥土)", "Right Leg (Mud)", true, "2" },
        { 9, false, "尾巴(泥土)", "Tail (Mud)", true, "1", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {30, {
        { 0, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "鬃毛", "Mane", true, "1" },
        { 3, false, "手臂", "Arms", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "腿", "Legs", false, "" },
        { 5, false, "尾巴", "Tail", false, "4", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {31, {
        { 0, true, "气囊", "Balloon", true, "1" },
        { 1, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "气囊", "Balloon", true, "" },
        { 3, false, "身体", "Body", false, "1" },
        { 4, false, "左腿", "Left Leg", false, "" },
        { 5, false, "右腿", "Right Leg", false, "" },
        { 6, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "右翼", "Right Wing", false, "1", {0x5u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 8, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {32, {
        { 0, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Body", false, "1" },
        { 2, false, "左翼", "Left Wing", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 3, false, "右翼", "Right Wing", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 4, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {33, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "手臂", "Arms", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "腿", "Legs", false, "" },
        { 5, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {34, {
        { 0, true, "反击", "Counterattack", true, "" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "1,2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "手臂", "Arms", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "腿", "Legs", false, "1" },
        { 6, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {35, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "???", "???", true, "" },
        { 2, true, "???", "???", true, "" },
        { 3, true, "???", "???", true, "" },
        { 4, true, "???", "???", true, "" },
        { 5, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 10, false, "颚", "Jaw", true, "1,2" },
        { 11, false, "背部", "Back", false, "1,2" },
        { 12, false, "左骨", "Left Bone", true, "1,2" },
        { 13, false, "右骨", "Right Bone", true, "1,2" },
    }},
    {36, {
        { 0, true, "排气", "Effluvia Emissions", true, "" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "背部", "Back", false, "" },
        { 4, false, "胸部", "Chest", true, "1", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "左臂", "Left Arm", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "" },
        { 9, false, "右腿", "Right Leg", false, "" },
        { 10, false, "翼", "Wings", false, "" },
    }},
    {37, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "5", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "手臂", "Arms", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "腿", "Legs", false, "" },
        { 5, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {38, {
        { 1, true, "角", "Horns", false, "1" },
        { 0, true, "角 #2", "Horns #2", true, "1" },
        { 2, false, "角", "Horns", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "胸部", "Chest", true, "", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "" },
        { 5, false, "左肢", "Left Limbs", true, "" },
        { 6, false, "右肢", "Right Limbs", true, "" },
        { 7, false, "尾巴", "Tail", false, "1", {0x7u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 8, false, "金角", "Golden Horns", true, "1" },
        { 9, false, "金鬃毛", "Golden Mane", true, "" },
        { 10, false, "黄金左胸", "Golden Left Chest", true, "1" },
        { 11, false, "黄金右胸", "Golden Right Chest", true, "1" },
        { 12, false, "黄金左臂", "Golden Left Arm", true, "1", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 13, false, "黄金右臂", "Golden Right Arm", true, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 14, false, "黄金左腿", "Golden Left Leg", true, "1", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 15, false, "黄金右腿", "Golden Right Leg", true, "1", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 16, false, "黄金尾巴（左）", "Golden Tail (Left)", true, "1" },
        { 17, false, "黄金尾巴（右）", "Golden Tail (Right)", true, "1" },
    }},
    {39, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "腿", "Legs", false, "", {0x3u, 0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {51, {
        { 0, true, "身体和腿", "Body & Legs", true, "1" },
        { 1, false, "鹿角", "Antlers", true, "1,2", {0x0u, 0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "", {0x0u, 0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "腿", "Legs", false, "" },
        { 4, false, "手臂", "Arms", false, "" },
        { 5, false, "???", "???", true, "" },
    }},
    {61, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "2", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右臂", "Right Arm", false, "2", {0x4u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {62, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "4", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "1", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右臂", "Right Arm", false, "1", {0x4u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {63, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "3", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "1", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右臂", "Right Arm", false, "1", {0x4u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {64, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "大退缩", "Big Flinch", true, "" },
        { 2, true, "反击", "Counterattack", true, "" },
        { 3, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "胸部", "Chest", true, "2" },
        { 6, false, "臀部", "Rear", false, "" },
        { 7, false, "手臂", "Arms", false, "" },
        { 8, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 10, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {65, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "4", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "2", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 4, false, "右臂", "Right Arm", false, "2", {0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {66, {
        { 1, true, "喉咙", "Throat", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "1,2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "鳍", "Fin", true, "1" },
        { 4, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "手臂", "Arms", false, "1" },
        { 6, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {67, {
        { 1, true, "喉咙", "Throat", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, true, "???", "???", true, "" },
        { 3, false, "头部", "Head", false, "1,2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "鳍", "Fin", true, "1" },
        { 5, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "手臂", "Arms", false, "1" },
        { 7, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {68, {
        { 1, true, "喉咙", "Throat", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "5", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "左腿", "Left Leg", false, "3", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右腿", "Right Leg", false, "3", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {69, {
        { 2, true, "头部", "Head", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "充气尾巴", "Inflated Tail", true, "" },
        { 3, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "1" },
        { 5, false, "左翼", "Left Wing", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右翼", "Right Wing", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {70, {
        { 0, true, "角", "Horns", false, "2,4" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, true, "???", "???", true, "" },
        { 3, true, "银尖刺（头）", "Silver Spikes (Head)", true, "1" },
        { 4, true, "银尖刺（左臂）", "Silver Spikes (L. Arm)", true, "1" },
        { 5, true, "银尖刺（右臂）", "Silver Spikes (R. Arm)", true, "1" },
        { 6, true, "银尖刺 (左翼)", "Silver Spikes (L. Wing)", true, "1" },
        { 7, true, "银尖刺 (右翼)", "Silver Spikes (R. Wing)", true, "1" },
        { 8, false, "角", "Horns", false, "" },
        { 9, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 10, false, "身体", "Body", false, "" },
        { 11, false, "左臂", "Left Arm", false, "", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 12, false, "右臂", "Right Arm", false, "", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 13, false, "左腿", "Left Leg", false, "" },
        { 14, false, "右腿", "Right Leg", false, "" },
        { 15, false, "左翼", "Left Wing", false, "", {0x2u, 0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 16, false, "右翼", "Right Wing", false, "", {0x6u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 17, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {71, {
        { 0, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "鬃毛", "Mane", true, "1" },
        { 3, false, "手臂", "Arms", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "腿", "Legs", false, "" },
        { 5, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {72, {
        { 0, true, "气囊", "Balloon", true, "1" },
        { 1, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "气囊", "Balloon", true, "" },
        { 3, false, "身体", "Body", false, "1" },
        { 4, false, "左腿", "Left Leg", false, "" },
        { 5, false, "右腿", "Right Leg", false, "" },
        { 6, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "右翼", "Right Wing", false, "1", {0x5u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 8, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {73, {
        { 0, true, "坠落", "Sky Fall", true, "" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左翼", "Left Wing", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 4, false, "右翼", "Right Wing", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "腿", "Legs", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {74, {
        { 0, true, "反击", "Counterattack", true, "" },
        { 2, true, "头部", "Head", false, "1,2" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 3, false, "头部", "Head", false, "", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "手臂", "Arms", false, "1", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "腿", "Legs", false, "1" },
        { 7, false, "尾巴", "Tail", false, "1", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {75, {
        { 1, true, "尾巴", "Tail", false, "1" },
        { 0, true, "排气", "Effluvia Emissions", true, "" },
        { 2, false, "头部", "Head", false, "3", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "背部", "Back", false, "" },
        { 4, false, "胸部", "Chest", true, "1", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "左臂", "Left Arm", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "1", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "" },
        { 9, false, "右腿", "Right Leg", false, "" },
        { 10, false, "翼", "Wings", false, "" },
        { 11, false, "???", "???", true, "" },
        { 12, false, "???", "???", true, "" },
        { 13, false, "???", "???", true, "" },
        { 14, false, "???", "???", true, "" },
        { 15, false, "???", "???", true, "" },
    }},
    {76, {
        { 1, true, "发光头", "Glowing Head", true, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, true, "发光尾巴", "Glowing Tail", true, "" },
        { 3, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "1" },
        { 5, false, "腿", "Legs", false, "", {0x3u, 0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 8, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {77, {
        { 0, true, "出雪（头）", "Emerge from Snow (Head)", true, "" },
        { 1, true, "出雪（身体）", "Emerge from Snow (Body)", true, "" },
        { 2, true, "出雪（尾巴）", "Emerge from Snow (Tail)", true, "" },
        { 3, false, "头部", "Head", false, "2", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "头部（雪）", "Head (Snow)", true, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "身体", "Body", false, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "身体（雪）", "Body (Snow)", true, "1", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "腿", "Legs", false, "2" },
        { 8, false, "尾巴", "Tail", false, "1", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 9, false, "尾巴（雪）", "Tail (Snow)", true, "1", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {78, {
        { 0, true, "角", "Horns", false, "1,2" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 2, true, "???", "???", true, "" },
        { 3, false, "角", "Horns", false, "", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "身体", "Body", false, "" },
        { 5, false, "左腿", "Left Leg", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "右腿", "Right Leg", false, "1", {0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {79, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, true, "坠落", "Sky Fall", true, "" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "头部（冰）", "Head (Ice)", true, "" },
        { 4, false, "身体", "Body", false, "" },
        { 5, false, "身体（冰）", "Body (Ice)", true, "" },
        { 6, false, "翼", "Wings", false, "2", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "翼（冰）", "Wings (Ice)", true, "" },
        { 8, false, "手臂", "Arms", false, "" },
        { 9, false, "手臂（冰）", "Arms (Ice)", true, "" },
        { 10, false, "腿", "Legs", false, "" },
        { 11, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {80, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "5", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "背部", "Back", false, "" },
        { 3, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "手臂", "Arms", false, "2", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "腿", "Legs", false, "" },
        { 6, false, "翼", "Wings", false, "2", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {81, {
        { 0, true, "头部（岩石）", "Head (Rock)", true, "1,2,3,4" },
        { 1, true, "头部（岩石）", "Head (Rock)", true, "1,2,3,4" },
        { 2, true, "胸部（岩石）", "Chest (Rock)", true, "1,2,3,4,5,6" },
        { 4, true, "???", "???", true, "" },
        { 3, true, "头部", "Head", false, "1" },
        { 5, false, "左颈（岩石）", "Neck Left (Rock)", true, "" },
        { 6, false, "右颈（岩石）", "Neck Right (Rock)", true, "" },
        { 7, false, "头部（岩石）", "Head (Rock)", true, "" },
        { 8, false, "尾巴（岩石）", "Tail (Rock)", true, "" },
        { 9, false, "左翼（岩石）", "Left Wing (Rock)", true, "1" },
        { 10, false, "右翼（岩石）", "Right Wing (Rock)", true, "1" },
        { 11, false, "左臂（岩石）", "Left Arm (Rock)", true, "1,2" },
        { 12, false, "右臂（岩石）", "Right Arm (Rock)", true, "1,2" },
        { 13, false, "腿", "Legs", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 14, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 15, false, "身体", "Body", false, "" },
        { 16, false, "左翼", "Left Wing", false, "" },
        { 17, false, "右翼", "Right Wing", false, "" },
        { 18, false, "左臂", "Left Arm", false, "1", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 19, false, "右臂", "Right Arm", false, "1", {0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 20, false, "尾巴", "Tail", false, "" },
    }},
    {87, {
        { 0, true, "角", "Horns", false, "1,2" },
        { 1, true, "尾巴", "Tail", false, "1" },
        { 3, true, "力量抑制", "Elemental Explosion", true, "3", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "头部", "Head", false, "", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "胸部", "Chest", true, "" },
        { 5, false, "翼", "Wings", false, "2", {0x2u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "手臂", "Arms", false, "", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "腿", "Legs", false, "", {0x3u, 0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 8, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {88, {
        { 1, true, "大退缩", "Big Flinch", true, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1" },
        { 4, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {89, {
        { 1, true, "大退缩", "Big Flinch", true, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "1" },
        { 4, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {90, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2,4", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 4, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {91, {
        { 0, true, "角", "Horns", false, "1" },
        { 2, true, "尾巴", "Tail", false, "1" },
        { 1, true, "角 #2", "Horns #2", true, "1" },
        { 3, true, "斗气硬化失效", "Rage", true, "" },
        { 4, false, "头部", "Head", false, "" },
        { 5, false, "身体", "Body", false, "" },
        { 6, false, "左臂", "Left Arm", false, "1", {0x0u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "1", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 9, false, "右腿", "Right Leg", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 10, false, "尾巴", "Tail", false, "" },
    }},
    {92, {
        { 0, true, "角", "Horns", false, "1" },
        { 2, true, "尾巴", "Tail", false, "" },
        { 1, true, "角 #2", "Horns #2", true, "1" },
        { 3, true, "斗气硬化失效", "Rage", true, "" },
        { 4, false, "头部", "Head", false, "" },
        { 5, false, "身体", "Body", false, "" },
        { 6, false, "左臂", "Left Arm", false, "1", {0x0u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右臂", "Right Arm", false, "1", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 9, false, "右腿", "Right Leg", false, "", {0x1u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 10, false, "尾巴", "Tail", false, "" },
    }},
    {93, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "1", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "2", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右臂", "Right Arm", false, "2", {0x4u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {94, {
        { 1, true, "充能角", "Charge", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2,4", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "背部", "Back", false, "1" },
        { 5, false, "手臂", "Arms", false, "2", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "腿", "Legs", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {95, {
        { 1, true, "充能角", "Charge", false, "" },
        { 0, true, "尾巴", "Tail", false, "1" },
        { 2, false, "头部", "Head", false, "2,4", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 3, false, "身体", "Body", false, "", {0x2u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "背部", "Back", false, "1" },
        { 5, false, "手臂", "Arms", false, "3", {0x1u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "腿", "Legs", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {96, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2", {0x0u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "背部", "Back", false, "" },
        { 4, false, "左臂", "Left Arm", false, "2", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "右臂", "Right Arm", false, "2", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 6, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 7, false, "右腿", "Right Leg", false, "", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 9, false, "尾巴尖", "Tail Tip", true, "" },
    }},
    {97, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "5,10", {0x0u, 0x4u, 0x8u, 0x9u}, 4u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "腹部", "Abdomen", true, "" },
        { 4, false, "背部", "Back", false, "1" },
        { 5, false, "胸部", "Chest", true, "1" },
        { 6, false, "左臂", "Left Arm", false, "7", {0x1u, 0xAu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "右臂", "Right Arm", false, "7", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "左腿", "Left Leg", false, "5", {0x2u, 0xCu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 9, false, "右腿", "Right Leg", false, "5", {0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 10, false, "左翼", "Left Wing", false, "3" },
        { 11, false, "右翼", "Right Wing", false, "3" },
        { 12, false, "尾巴", "Tail", false, "", {0x3u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {98, {
        { 0, false, "???", "???", true, "", {0x0u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 1, false, "???", "???", true, "", {0x1u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 2, false, "???", "???", true, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
    }},
    {99, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "2,4", {0x0u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "1" },
        { 3, false, "左腿", "Left Leg", false, "", {0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 4, false, "右腿", "Right Leg", false, "", {0x8u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 5, false, "左翼", "Left Wing", false, "1", {0x1u, 0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "右翼", "Right Wing", false, "1", {0x6u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "尾巴", "Tail", false, "", {0x4u, 0x9u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {100, {
        { 0, true, "尾巴", "Tail", false, "1" },
        { 1, false, "头部", "Head", false, "1,2", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "身体", "Body", false, "" },
        { 3, false, "左臂", "Left Arm", false, "2", {0x1u, 0x6u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 4, false, "右臂", "Right Arm", false, "2", {0x4u, 0x7u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 5, false, "左腿", "Left Leg", false, "" },
        { 6, false, "右腿", "Right Leg", false, "" },
        { 7, false, "尾巴", "Tail", false, "", {0x2u, 0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
    }},
    {101, {
        { 0, true, "击倒", "Knockdown", true, "" },
        { 1, false, "头部", "Head", false, "3,6", {0x0u, 0x3u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 2, false, "颈部", "Neck", false, "" },
        { 3, false, "胸部", "Chest", true, "2" },
        { 4, false, "身体", "Body", false, "" },
        { 5, false, "左臂", "Left Arm", false, "", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 6, false, "右臂", "Right Arm", false, "", {0x1u, 0x4u, 0xFFFFFFFFu, 0xFFFFFFFFu}, 2u },
        { 7, false, "左腿", "Left Leg", false, "", {0x2u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 8, false, "右腿", "Right Leg", false, "", {0x5u, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu}, 1u },
        { 9, false, "左翼", "Left Wing", false, "1" },
        { 10, false, "右翼", "Right Wing", false, "1" },
        { 11, false, "尾巴", "Tail", false, "" },
    }},
};
// END AUTO-GENERATED kPartSchemas

// HunterPie MonsterData.xml Ailment Id -> Chinese name (fixed, not per-TU).
extern const QHash<int, QString> kAilmentNames = {
    {1, QStringLiteral("毒")},
    {2, QStringLiteral("麻痹")},
    {3, QStringLiteral("睡眠")},
    {4, QStringLiteral("爆破")},
    {5, QStringLiteral("乘骑")},
    {6, QStringLiteral("疲劳")},
    {7, QStringLiteral("眩晕")},
    {8, QStringLiteral("捕获")},
    {9, QStringLiteral("闪光")},
    {10, QStringLiteral("闪光")},   // AILMENT_FLASH — duplicate id in MonsterData.xml
    {11, QStringLiteral("倒地")},
    {14, QStringLiteral("麻痹陷阱")},
    {15, QStringLiteral("落穴陷阱")},
    {16, QStringLiteral("藤蔓陷阱")},
    {18, QStringLiteral("龙封")},
    {22, QStringLiteral("爪击")},
    {23, QStringLiteral("口水硬直")},
};

// v0.9 i18n (WS-A): English column for the World monster-ailment table
// above. Keys are Game/World/Data/MonsterData.xml <Ailments> ids; every
// string is the official en-us.xml <Ailments><Rise><Ailment Id="AILMENT_*">
// value for the matching AILMENT_* key (the ailment enum is shared by both
// games, so World's AILMENT_POISON / AILMENT_CLAWFLINCH etc. resolve there).
// The zh table stays authoritative for Chinese and is never consulted here:
// a locale-aware caller picks exactly one of the two tables.
extern const QHash<int, QString> kAilmentNamesEn = {
    {1,  QStringLiteral("Poison")},       // AILMENT_POISON
    {2,  QStringLiteral("Paralysis")},    // AILMENT_PARALYSIS
    {3,  QStringLiteral("Sleep")},        // AILMENT_SLEEP
    {4,  QStringLiteral("Blast")},        // AILMENT_BLAST
    {5,  QStringLiteral("Mount")},        // AILMENT_MOUNT
    {6,  QStringLiteral("Exhaust")},      // AILMENT_EXHAUST
    {7,  QStringLiteral("Stun")},         // AILMENT_STUN
    {8,  QStringLiteral("Tranquilize")},  // AILMENT_TRANQUILIZE
    {9,  QStringLiteral("Flash")},        // AILMENT_FLASH
    {10, QStringLiteral("Flash")},        // AILMENT_FLASH — duplicate id, as in zh
    {11, QStringLiteral("Knockdown")},    // AILMENT_KNOCKDOWN
    // Ids below are absent from the zh table: the reader's fallback there is
    // "异常%1". English gets the official names so the EN overlay shows a
    // real label instead of "Ailment N". zh behaviour is unchanged.
    {12, QStringLiteral("Dung Bomb")},    // AILMENT_DUNG
    {14, QStringLiteral("Shock Trap")},   // AILMENT_SHOCKTRAP
    {15, QStringLiteral("Pitfall Trap")}, // AILMENT_PITFALLTRAP
    {16, QStringLiteral("Vine Trap")},    // AILMENT_VINETRAP
    {18, QStringLiteral("Elderseal")},    // AILMENT_ELDERSEAL
    {19, QStringLiteral("Smoking")},      // AILMENT_SMOKING
    {21, QStringLiteral("Felyne Trap")},  // AILMENT_FELYNETRAP
    {22, QStringLiteral("Clutch Claw")},  // AILMENT_CLAW
    {23, QStringLiteral("Claw Flinch")},  // AILMENT_CLAWFLINCH
    {24, QStringLiteral("Banishing Ball")}, // AILMENT_BANISHINGBALL
};

// v0.7.5: Rise ailment SLOT ids (positional, 0-16) from HunterPie
// Game/Rise/Data/MonsterData.xml <Ailments>. NOTE the ordering differs
// from World's kAilmentNames (World 1=poison; Rise 4=poison).
extern const QHash<int, QString> kRiseAilmentNames = {
    { 0, QStringLiteral("麻痹")},
    { 1, QStringLiteral("睡眠")},
    { 2, QStringLiteral("眩晕")},
    { 3, QStringLiteral("闪光")},
    { 4, QStringLiteral("毒")},
    { 5, QStringLiteral("爆破")},
    { 6, QStringLiteral("疲劳")},
    { 7, QStringLiteral("乘骑")},
    { 8, QStringLiteral("水异常")},
    { 9, QStringLiteral("火异常")},
    {10, QStringLiteral("冰异常")},
    {11, QStringLiteral("雷异常")},
    {12, QStringLiteral("落穴陷阱")},
    {13, QStringLiteral("麻痹陷阱")},
    {14, QStringLiteral("捕获")},
    {15, QStringLiteral("异臭")},
    {16, QStringLiteral("钢龙毒")},
};

// Generated from HunterPie Game/World/Data/MonsterData.xml <Crowns> thresholds.
// Per-monster crown size thresholds: {Mini, Silver, Gold}.
extern const QHash<int, std::array<float, 3>> kCrownThresholds = {
    {0, {0.90F, 1.10F, 1.20F}},
    {1, {0.90F, 1.15F, 1.23F}},
    {4, {0.90F, 1.15F, 1.23F}},
    {7, {0.90F, 1.15F, 1.23F}},
    {9, {0.90F, 1.15F, 1.23F}},
    {10, {0.90F, 1.15F, 1.23F}},
    {11, {0.90F, 1.15F, 1.23F}},
    {12, {0.90F, 1.15F, 1.23F}},
    {13, {0.90F, 1.15F, 1.23F}},
    {14, {0.90F, 1.15F, 1.23F}},
    {15, {0.90F, 1.15F, 1.23F}},
    {16, {0.90F, 1.15F, 1.23F}},
    {17, {0.90F, 1.15F, 1.23F}},
    {18, {0.90F, 1.15F, 1.23F}},
    {19, {0.90F, 1.15F, 1.23F}},
    {20, {0.90F, 1.10F, 1.20F}},
    {21, {0.90F, 1.15F, 1.23F}},
    {22, {0.90F, 1.10F, 1.20F}},
    {23, {0.90F, 1.15F, 1.23F}},
    {24, {0.90F, 1.10F, 1.20F}},
    {25, {0.90F, 1.15F, 1.23F}},
    {26, {0.90F, 1.15F, 1.23F}},
    {27, {0.90F, 1.15F, 1.23F}},
    {28, {0.90F, 1.15F, 1.23F}},
    {29, {0.90F, 1.15F, 1.23F}},
    {30, {0.90F, 1.10F, 1.20F}},
    {31, {0.90F, 1.15F, 1.23F}},
    {32, {0.90F, 1.15F, 1.23F}},
    {33, {0.90F, 1.15F, 1.23F}},
    {34, {0.90F, 1.15F, 1.23F}},
    {35, {0.90F, 1.10F, 1.20F}},
    {36, {0.90F, 1.15F, 1.23F}},
    {37, {0.90F, 1.15F, 1.23F}},
    {38, {0.90F, 1.15F, 1.23F}},
    {39, {0.90F, 1.15F, 1.23F}},
    {51, {0.90F, 1.15F, 1.23F}},
    {61, {0.90F, 1.15F, 1.23F}},
    {62, {0.90F, 1.15F, 1.23F}},
    {63, {0.90F, 1.15F, 1.23F}},
    {64, {0.99F, 1.14F, 1.20F}},
    {65, {0.90F, 1.15F, 1.23F}},
    {66, {0.90F, 1.10F, 1.20F}},
    {67, {0.90F, 1.10F, 1.20F}},
    {68, {0.90F, 1.10F, 1.20F}},
    {69, {0.90F, 1.10F, 1.20F}},
    {70, {0.90F, 1.15F, 1.23F}},
    {71, {0.90F, 1.10F, 1.20F}},
    {72, {0.90F, 1.15F, 1.23F}},
    {73, {0.90F, 1.15F, 1.23F}},
    {74, {0.90F, 1.15F, 1.23F}},
    {75, {0.90F, 1.15F, 1.23F}},
    {76, {0.90F, 1.15F, 1.23F}},
    {77, {0.90F, 1.15F, 1.23F}},
    {78, {0.90F, 1.15F, 1.23F}},
    {79, {0.90F, 1.15F, 1.23F}},
    {80, {0.90F, 1.15F, 1.23F}},
    {81, {0.90F, 1.15F, 1.23F}},
    {87, {0.90F, 1.15F, 1.23F}},
    {88, {0.90F, 1.15F, 1.23F}},
    {89, {0.90F, 1.15F, 1.23F}},
    {90, {0.90F, 1.15F, 1.23F}},
    {91, {0.90F, 1.11F, 1.18F}},
    {92, {0.90F, 1.11F, 1.18F}},
    {93, {0.90F, 1.15F, 1.23F}},
    {94, {0.90F, 1.15F, 1.23F}},
    {95, {0.90F, 1.15F, 1.23F}},
    {96, {0.90F, 1.15F, 1.23F}},
    {97, {0.90F, 1.15F, 1.23F}},
    {98, {0.90F, 1.15F, 1.23F}},
    {99, {0.90F, 1.15F, 1.23F}},
    {100, {0.90F, 1.15F, 1.23F}},
    {101, {0.90F, 1.15F, 1.23F}},
};


// Generated from HunterPie Game/Rise/Data/MonsterData.xml <Crowns>.
// This table deliberately includes only explicit Rise <Crowns> entries; no
// World default is substituted for a missing Rise element or attribute.
extern const QHash<int, std::array<float, 3>> kRiseCrownThresholds = {
    {1, {0.96F, 1.1F, 1.14F}},
    {3, {0.97F, 1.17F, 0.0F}},
    {4, {0.0F, 1.09F, 1.14F}},
    {7, {0.97F, 1.17F, 0.0F}},
    {8, {0.97F, 1.17F, 0.0F}},
    {9, {0.97F, 1.17F, 0.0F}},
    {10, {0.97F, 1.17F, 0.0F}},
    {11, {0.97F, 1.17F, 0.0F}},
    {19, {0.97F, 1.17F, 0.0F}},
    {22, {0.96F, 1.03F, 1.05F}},
    {26, {0.96F, 1.1F, 1.14F}},
    {27, {0.0F, 1.11F, 1.17F}},
    {29, {0.0F, 1.09F, 1.14F}},
    {30, {0.765F, 0.9775F, 1.0455F}},
    {76, {0.97F, 1.17F, 0.0F}},
    {77, {0.97F, 1.17F, 0.0F}},
    {80, {0.97F, 1.17F, 0.0F}},
    {81, {0.97F, 1.17F, 0.0F}},
    {82, {0.0F, 1.11F, 1.17F}},
    {83, {0.0F, 1.11F, 1.17F}},
    {86, {0.97F, 1.17F, 0.0F}},
    {87, {0.0F, 1.11F, 1.17F}},
    {88, {0.0F, 1.09F, 1.14F}},
    {93, {0.0F, 1.11F, 1.17F}},
    {95, {0.0F, 1.11F, 1.17F}},
    {107, {0.97F, 1.17F, 0.0F}},
    {108, {0.97F, 1.17F, 0.0F}},
    {109, {0.97F, 1.17F, 0.0F}},
    {110, {0.0F, 1.11F, 1.17F}},
    {111, {0.0F, 1.11F, 1.17F}},
    {112, {0.0F, 1.11F, 1.17F}},
    {113, {0.0F, 1.11F, 1.17F}},
    {114, {0.97F, 1.15F, 0.0F}},
};

// Generated from HunterPie Game/Rise/Data/MonsterData.xml
// <Monster IsNotCapturable="true">. Rise provides no Capture=N percentage.
extern const QSet<int> kRiseNotCapturableMonsterIds = {
    1,
    3,
    7,
    9,
    10,
    11,
    19,
    22,
    26,
    27,
    35,
    38,
    39,
    46,
    83,
    93,
    96,
    111,
    112,
    114,
    115,

};

// Generated from HunterPie Game/World/Data/MonsterData.xml <Monster Capture=N>.
// Each entry is the in-game HP percentage at which that monster becomes
// capturable (0 = uncapturable, e.g. Elder Dragons). Drives the red HP
// bar colour in MonsterPanel when current HP drops to or below this %.
extern const QHash<int, int> kMonsterCaptureThresholds = {
    { 0, 25 }, { 1, 20 }, { 4,  0 }, { 7, 30 }, { 9, 25 }, { 10, 25 },
    { 11, 15 }, { 12, 20 }, { 13, 15 }, { 14,  0 }, { 15,  0 }, { 16,  0 },
    { 17,  0 }, { 18,  0 }, { 19, 20 }, { 20, 20 }, { 21, 25 }, { 22, 20 },
    { 23,  0 }, { 24, 25 }, { 25,  0 }, { 26,  0 }, { 27, 30 }, { 28, 30 },
    { 29, 25 }, { 30, 25 }, { 31, 25 }, { 32, 20 }, { 33, 30 }, { 34, 20 },
    { 35, 25 }, { 36,  0 }, { 37, 30 }, { 38,  0 }, { 39, 30 }, { 51,  0 },
    { 61, 20 }, { 62, 20 }, { 63, 20 }, { 64, 10 }, { 65, 20 }, { 66, 20 },
    { 67, 20 }, { 68, 15 }, { 69, 25 }, { 70,  0 }, { 71, 25 }, { 72, 25 },
    { 73, 15 }, { 74, 15 }, { 75,  0 }, { 76, 10 }, { 77, 25 }, { 78, 25 },
    { 79,  0 }, { 80,  0 }, { 81,  0 }, { 87,  0 }, { 88, 10 }, { 89, 10 },
    { 90, 20 }, { 91, 15 }, { 92, 10 }, { 93, 15 }, { 94, 20 }, { 95, 20 },
    { 96,  0 }, { 97,  0 }, { 98,  0 }, { 99, 15 }, { 100, 20 }, { 101,  0 },
};

} // namespace mhw